# https://riptutorial.com/docker-compose
# sudo docker compose --file docker-compose.yml up -d
# Update to the latest image:
# sudo docker compose pull && sudo docker-compose up -d
# https://docs.docker.com/compose/reference/
version: '3.1'

services:

  db:
    image: postgres
    volumes:
      # Will persist container's /var/lib/postgresql/data folder to host's ./plan/db/ folder
      - "./plan/db:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: rosario
      POSTGRES_PASSWORD: rosariopwd
      POSTGRES_DB: rosariosis

  web:
    image: rosariosis/rosariosis:master
    #build: .
    ports:
      # host:container
      - "80:80"
    depends_on:
      - db
    volumes:
      # Will persist container's /var/www/html folder to host's ./plan/rosariosis/ folder
      - "./plan/rosariosis:/var/www/html"
    environment:
      PGHOST: db
      PGUSER: rosario
      PGPASSWORD: rosariopwd
      PGDATABASE: rosariosis
      ROSARIOSIS_YEAR: 2022
#      ROSARIOSIS_LANG: 'es_ES'
