# https://riptutorial.com/docker-compose
version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: rosario
      POSTGRES_PASSWORD: rosariopwd
      POSTGRES_DB: rosariosis

  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      PGHOST: db
      PGUSER: rosario
      PGPASSWORD: rosariopwd
      PGDATABASE: rosariosis
      ROSARIOSIS_YEAR: 2022
#      ROSARIOSIS_LANG: 'es_ES'
